# Generated by Django 5.1.6 on 2025-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lenght',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_create',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_end',
            field=models.DateField(),
        ),
    ]
